Repository hmcts/em-stitching-api, pull requests merged in 2020-12, with the labels that each got.

#485 EM-3283 - Stitching API - Suppress nightly jobs dependency vulnerabil…
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-485

#486 Resolved vulnerability
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-486

#488 EM-3264 - EM-Stitching: Add retry logic for failing functional test c…
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleFolderScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleOptionScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleOutlineScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/DocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/OpenIdConnectScenarios.java
Labels: ns:em, prd:em, rel:em-stitching-pr-488

#497 Resolved vulnerabilities
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-497

#499 EM-3302 - Stitching API - Suppress nightly jobs dependency vulnerabil…
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-499
