Repository hmcts/em-stitching-api, pull requests merged in 2021-03, with the labels that each got.

#561 Resolved CVE-2021-22112
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-561

#569 Resolved CVE-2021-25122, CVE-2021-25329
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-569

#568 Updated Jupiter and Pact related dependencies
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-568

#551 Added in Callback retry logic
  build.gradle
  charts/em-stitching/Chart.yaml
  charts/em-stitching/values.yaml
  src/main/java/uk/gov/hmcts/reform/em/stitching/batch/DocumentTaskCallbackProcessor.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/Callback.java
  src/main/resources/application.yaml
  src/main/resources/db/db.changelog-master.xml
  src/test/java/uk/gov/hmcts/reform/em/stitching/batch/DocumentTaskCallbackProcessorTest.java
Labels: ns:em, prd:em, rel:em-stitching-pr-551

#579 Fixed CVE-2020-15824, CVE-2020-29582
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-579
