Repository hmcts/em-stitching-api, pull requests merged in 2021-01, with the labels that each got.

#513 Added in ingressHost
  charts/em-stitching/Chart.yaml
  charts/em-stitching/values.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-513

#518 Resolved Vulnerability
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-518

#519 Fix sonar issue
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-519

#522 EM-3425 - EM-Stitching API- Failed to generate serenity report
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-522
