Repository hmcts/em-stitching-api, pull requests merged in 2021-12, with the labels that each got.

#812 Fixed log4J vulnerability
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-812

#813 Updated log4J version
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-813

#815 Update fortify scan
  Jenkinsfile_nightly
  config/fortify-client.properties
Labels: ns:em, prd:em, rel:em-stitching-pr-815
