Repository hmcts/em-stitching-api, pull requests merged in 2021-02, with the labels that each got.

#533 Resolved vulnerability
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-533

#540 Resolved CVE-2021-21290
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-540

#541 EM-3527 - Stitching API - Suppress nightly jobs dependency vulnerabil…
  audit.json
Labels: ns:em, prd:em, rel:em-stitching-pr-541

#548 Resolved Sonar issue
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-548

#549 fix sonar coverage
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-549

#552 update docmosis-development url to use aks version
  charts/em-stitching/Chart.yaml
  charts/em-stitching/values.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-552

#553 Updated terraform and gradle version
  gradle/wrapper/gradle-wrapper.properties
  infrastructure/.terraform-version
Labels: ns:em, prd:em, rel:em-stitching-pr-553
