Repository hmcts/em-stitching-api, pull requests merged in 2021-06, with the labels that each got.

#647 Fixed Resource leak issue
  src/main/java/uk/gov/hmcts/reform/em/stitching/rest/DocumentTaskResource.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/template/DocmosisClient.java
Labels: ns:em, prd:em, rel:em-stitching-pr-647

#652 Updated em-test-helper version
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-652

#654 Fixed CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-654

#656 Em 3849 wrap text
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleFolderScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleOptionScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleOutlineScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/testutil/TestUtil.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMerger.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFUtility.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMergerTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMergerTestUtil.java
Labels: ns:em, prd:em, rel:em-stitching-pr-656

#671 reordering security.sh
  security.sh
Labels: ns:em, prd:em, rel:em-stitching-pr-671
