Repository hmcts/em-stitching-api, pull requests merged in 2021-11, with the labels that each got.

#774 Resolve "CVE-2021-22096"
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-774

#775 EM-4112: adding forced postgresql version
  infrastructure/main.tf
Labels: ns:em, prd:em, rel:em-stitching-pr-775

#776 Fix CVE-2021-22044
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-776

#723 Added in CDAM changes
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  bin/idam-client-setup-roles.sh
  bin/start-local-environment.sh
  build.gradle
  charts/em-stitching/Chart.yaml
  charts/em-stitching/values.yaml
  docker-compose-dependencies.yml
  idam-client-setup.sh
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BaseTest.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/SecureDocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/testutil/ExtendedCcdHelper.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/testutil/TestUtil.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/testutil/dto/CcdBundleDocumentDTO.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/testutil/dto/CcdDocument.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/testutil/dto/CcdValue.java
  src/aat/resources/adv_stitching_functional_tests_ccd_def.xlsx
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/stitching/batch/DocumentTaskItemProcessor.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/Bundle.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/DocumentTask.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/service/CdamService.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/service/EmCaseDocumentClientApi.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/service/dto/BundleDTO.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/service/dto/ByteArrayMultipartFile.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/service/dto/DocumentTaskDTO.java
  src/main/resources/application.yaml
  src/main/resources/db/db.changelog-master.xml
  src/test/java/uk/gov/hmcts/reform/em/stitching/batch/DocumentTaskItemProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/service/CdamServiceTest.java
  src/test/resources/one-page.pdf
  src/test/resources/wordDocument2.docx
Labels: ns:em, prd:em, rel:em-stitching-pr-723

#789 Updated column size for failure_description field
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/DocumentTask.java
  src/main/resources/db/db.changelog-master.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-789
