Repository hmcts/em-stitching-api, pull requests merged in 2022-08, with the labels that each got.

#1061 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-1061

#1069 Flyway migration on AAT & Prod
  README.md
  build.gradle
  charts/em-stitching/Chart.yaml
  charts/em-stitching/values.aat.template.yaml
  charts/em-stitching/values.preview.template.yaml
  charts/em-stitching/values.yaml
  gradle.properties
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/stitching/config/FlywayConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/data/migration/FlywayNoOpStrategy.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/data/migration/PendingMigrationScriptException.java
  src/main/resources/application.yaml
  src/main/resources/db/db.changelog-master.xml
  src/main/resources/db/migration/V1__baseline_migration.sql
  src/main/resources/liquibase.properties
  src/test/resources/config/application.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-1069

#1071 Resolved fortify issue
  docker-compose-dependencies-simulator.yml
  docker-compose-dependencies.yml
  docker-compose.yml
  docker-pactbroker-compose.yml
Labels: ns:em, prd:em, rel:em-stitching-pr-1071

#1077 Resolve preview secret issue
  charts/em-stitching/Chart.yaml
  charts/em-stitching/values.preview.template.yaml
  charts/em-stitching/values.yaml
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-1077

#1080 Increased DB storage size for Perftest & Prod
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:em, prd:em, add-or-update, rel:em-stitching-pr-1080

#1091 Add backstage configuration file
  catalog-info.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-1091
