Repository hmcts/em-stitching-api, pull requests merged in 2022-10, with the labels that each got.

#1203 EM-4689 remove unused log config
  build.gradle
  charts/em-stitching/Chart.yaml
  charts/em-stitching/values.yaml
  src/main/resources/logback-spring.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-1203

#1209 comment out sync branches with master
  Jenkinsfile_CNP
Labels: ns:em, prd:em, rel:em-stitching-pr-1209

#1213 Add created date index for document task
  build.gradle
  src/main/resources/db/migration/V2__document_task_created_date_index.sql
  src/test/resources/config/application.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-1213, Do Not Merge
