Repository hmcts/em-stitching-api, pull requests merged in 2022-01, with the labels that each got.

#831 Updated log4J version
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-831

#828 Added in changes to remove old DocumentTask records
  build.gradle
  charts/em-stitching/Chart.yaml
  charts/em-stitching/values.yaml
  src/main/java/uk/gov/hmcts/reform/em/stitching/batch/RemoveOldDocumentTaskTasklet.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/config/BatchConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/repository/DocumentTaskRepository.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/stitching/batch/RemoveOldDocumentTaskTaskletTest.java
Labels: ns:em, prd:em, rel:em-stitching-pr-828

#835 Swapped secrets for v11 DB
  Jenkinsfile_CNP
  charts/em-stitching/Chart.yaml
  charts/em-stitching/values.yaml
  infrastructure/main.tf
Labels: ns:em, prd:em, rel:em-stitching-pr-835

#837 Increased DB CPU core for Prod
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:em, prd:em, rel:em-stitching-pr-837

#844 Added index for versioned_document_task table
  src/main/resources/db/db.changelog-master.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-844

#845 Upgrade gradle to 7.3.3
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: ns:em, prd:em, rel:em-stitching-pr-845

#848 Updated java version to 17
  Dockerfile
  build.gradle
  charts/em-stitching/Chart.yaml
  src/aat/java/uk/gov/hmcts/reform/em/stitching/testutil/TestUtil.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/domain/BundleTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/domain/CallbackTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/domain/EntityAuditEventTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/repository/CustomAuditEventRepositoryIntTest.java
  web.config
Labels: ns:em, prd:em, rel:em-stitching-pr-848

#849 Added in am-role-assignment-service docker dependency
  bin/start-local-environment.sh
  docker-compose-dependencies.yml
Labels: ns:em, prd:em, rel:em-stitching-pr-849

#851 Reverted java 17 version changes
  Dockerfile
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-851

#852 Delete the secret token
  docker-compose-dependencies.yml
Labels: ns:em, prd:em, rel:em-stitching-pr-852

#836 Removed v9.6 DB details
  infrastructure/main.tf
Labels: ns:em, prd:em, rel:em-stitching-pr-836

#861 Increased CPU Core for DB for AAT
  infrastructure/aat.tfvars
Labels: ns:em, prd:em, rel:em-stitching-pr-861
