Repository hmcts/em-stitching-api, pull requests merged in 2022-04, with the labels that each got.

#928 Suppressed CVE
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-928

#932 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-932

#938 Updated Swagger Doc
  src/main/java/uk/gov/hmcts/reform/em/stitching/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/rest/DocumentTaskResource.java
Labels: ns:em, prd:em, rel:em-stitching-pr-938

#942 Fix security scan
  audit.json
Labels: ns:em, prd:em, rel:em-stitching-pr-942
