Repository hmcts/em-stitching-api, pull requests merged in 2022-09, with the labels that each got.

#1103 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-1103

#1060 Upgrade to Java 17
  Dockerfile
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-1060

#1105 Upgrade pitest plugin
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-1105

#1112 EM-4226-trying-to-fix-mutation-test
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-1112

#1114 Added in dependabot config
  .github/dependabot.yml
  .github/stale.yml
  renovate.json
Labels: ns:em, prd:em, rel:em-stitching-pr-1114

#1128 Em 4226 fix pitest
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-1128

#1143 EM-4595 copy app-insights-connection-string from rpa to em-stitching
  infrastructure/main.tf
Labels: ns:em, prd:em, add-or-update, rel:em-stitching-pr-1143

#1144 Use em-test-helper version 1.21.4
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-1144

#1170 increase timeout for feign
  charts/em-stitching/Chart.yaml
  charts/em-stitching/values.yaml
  src/main/java/uk/gov/hmcts/reform/em/stitching/service/EmCaseDocumentClientApi.java
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-1170

#1171 EM-4586 change http client
  charts/em-stitching/Chart.yaml
  charts/em-stitching/values.yaml
  src/main/java/uk/gov/hmcts/reform/em/stitching/batch/DocumentTaskItemProcessor.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/config/HttpClientConfiguration.java
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-1171

#1178 EM-4586 change log
  src/main/java/uk/gov/hmcts/reform/em/stitching/batch/DocumentTaskItemProcessor.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1178
