Repository hmcts/em-stitching-api, pull requests merged in 2022-03, with the labels that each got.

#889 Removed suppressions
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-889

#891 update postgres version to 11 for local setup
  database/Dockerfile
Labels: ns:em, prd:em, rel:em-stitching-pr-891

#892 bump java chart
  charts/em-stitching/Chart.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-892

#890 Updated SpringBoot version to 2.6.4
  build.gradle
  src/main/java/uk/gov/hmcts/reform/em/stitching/Application.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/config/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMerger.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/rest/DocumentTaskResource.java
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-890

#893 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-893

#903 [EM-4315]-Security Scan Fix
  audit.json
Labels: ns:em, prd:em, em-automation, rel:em-stitching-pr-903

#904 Updated column name to resolve reserve word issue
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/PersistentAuditEvent.java
  src/main/resources/db/db.changelog-master.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-904

#905 Resolved CVE
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-905

#909 Fix Dependency Check
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-909

#911 Updated dependabot.yml
  .github/dependabot.yml
Labels: ns:em, prd:em, rel:em-stitching-pr-911

#914 EM-4341 - changed fasterXmlJackson from 2.13.1 to 2.13.2 and added ja…
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-914

#910 Code improvements
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMerger.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFUtility.java
Labels: ns:em, prd:em, rel:em-stitching-pr-910

#917 Remove jackson-bom
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-917

#919 Updated azurerm version
  infrastructure/state.tf
Labels: ns:em, prd:em, rel:em-stitching-pr-919
