Repository hmcts/em-stitching-api, pull requests merged in 2023-01, with the labels that each got.

#1309 EM-4912-suppress-vulnerability
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-1309

#1302 EM-4701 query issue
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/Bundle.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/BundleFolder.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1302

#1321 Suppress CVE
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-1321

#1322 EM-4943 suppress vulnerability
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-1322

#1288 Em-4849 index file folder issue
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleFolderScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/DocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/SecureDocumentTaskScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/Bundle.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/BundleContainer.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/BundleFolder.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMerger.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFWatermark.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/template/DocmosisClient.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/domain/BundleTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMergerTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMergerTestUtil.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1288

#1336 EM-4960 refactor log
  src/main/java/uk/gov/hmcts/reform/em/stitching/batch/DocumentTaskCallbackProcessor.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/batch/DocumentTaskItemProcessor.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1336

#1351 Updated perftest DB infrastructure details to match prod config
  infrastructure/perftest.tfvars
Labels: ns:em, prd:em, add-or-update, rel:em-stitching-pr-1351

#1352 EM-4988 add log
  src/main/java/uk/gov/hmcts/reform/em/stitching/batch/DocumentTaskItemProcessor.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMerger.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/service/CdamService.java
Labels: ns:em, prd:em, add-or-update, rel:em-stitching-pr-1352

#1359 EM-5015 bump-hmcts.java
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-1359

#1349 Memory issue resolution changes
  src/main/java/uk/gov/hmcts/reform/em/stitching/batch/DocumentTaskItemProcessor.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/service/impl/DocumentConversionServiceImpl.java
Labels: ns:em, prd:em, add-or-update, rel:em-stitching-pr-1349

#1362 EM-5019 fix pipeline
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:em, prd:em, rel:em-stitching-pr-1362
