Repository hmcts/em-stitching-api, pull requests merged in 2023-10, with the labels that each got.

#1812 Removed v14 DB details
  config/owasp/dependency-check-suppressions.xml
  infrastructure/main.tf
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleFolderScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleOptionScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleOutlineScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/DocumentTaskScenarios.java
Labels: ns:em, prd:em, destroy, rel:em-stitching-pr-1812

#1815 Added in v15 db details for non-prod env
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
Labels: ns:em, prd:em, add-or-update, rel:em-stitching-pr-1815

#1813 Resolve CVE-2023-4586
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, add-or-update, rel:em-stitching-pr-1813

#1832 EM-5616 CVE-2023-5072 vulnerability
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-1832

#1842 EM-5505 reduce logs
  lib/applicationinsights.json
  src/main/java/uk/gov/hmcts/reform/em/stitching/batch/RemoveOldDocumentTaskTasklet.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/validation/CallableEndpointValidator.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1842
