Repository hmcts/em-stitching-api, pull requests merged in 2023-04, with the labels that each got.

#1485 EM-5186 remove security.sh
  security.sh
Labels: ns:em, prd:em, rel:em-stitching-pr-1485

#1486 EM-5186 increase test coverage
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFOutlineTest.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1486

#1488 Em-5186 suppress sec scan vulnerability
  audit.json
Labels: ns:em, prd:em, rel:em-stitching-pr-1488

#1495 EM-5198 security scan
  audit.json
  functional-output/zap.reports
Labels: ns:em, prd:em, rel:em-stitching-pr-1495

#1496 Welcome endpoint to return JSON response
  src/aat/java/uk/gov/hmcts/reform/em/stitching/smoke/SmokeTest.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/rest/WelcomeResource.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/rest/WelcomeResourceTest.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1496

#1499 EM-5198 suppress sec scan vulnerability
  audit.json
Labels: ns:em, prd:em, rel:em-stitching-pr-1499
