Repository hmcts/em-stitching-api, pull requests merged in 2023-09, with the labels that each got.

#1714 Resolve CVE-2023-41080
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-1714

#1715 Added in v14 db details
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:em, prd:em, add-or-update, rel:em-stitching-pr-1715

#1717 Ignored functional tests
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/SecureDocumentTaskScenarios.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1717

#1698 Upgrade to pdfbox 3
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleFolderScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleOutlineScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/DocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/SecureDocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/testutil/TestUtil.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/Bundle.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMerger.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFOutline.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFUtility.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFWatermark.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/TableOfContents.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/template/DocmosisClient.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMergerCoversheetsTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMergerTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFOutlineTest.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1698

#1720 Revert "Upgrade to pdfbox 3 (#1698)"
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleFolderScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleOutlineScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/DocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/SecureDocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/testutil/TestUtil.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/Bundle.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMerger.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFOutline.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFUtility.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFWatermark.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/TableOfContents.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/template/DocmosisClient.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMergerCoversheetsTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMergerTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFOutlineTest.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1720

#1724 Update AAT DB size
  infrastructure/aat.tfvars
Labels: ns:em, prd:em, add-or-update, rel:em-stitching-pr-1724

#1725 Reverted v14 db details
  infrastructure/main.tf
Labels: ns:em, prd:em, destroy, rel:em-stitching-pr-1725

#1726 Revert "EM-5537 check duplicate keys (#1722)"
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleFolderScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleOutlineScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/DocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/SecureDocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/testutil/TestUtil.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/Bundle.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMerger.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFOutline.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFUtility.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFWatermark.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/TableOfContents.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/template/DocmosisClient.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMergerCoversheetsTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMergerTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFOutlineTest.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1726

#1727 fix broken query
  src/main/java/uk/gov/hmcts/reform/em/stitching/batch/RemoveSpringBatchHistoryTasklet.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1727

#1732 Added in v14 db extensions
  infrastructure/main.tf
Labels: ns:em, prd:em, destroy, rel:em-stitching-pr-1732

#1733 remove logs
  src/main/java/uk/gov/hmcts/reform/em/stitching/batch/RemoveSpringBatchHistoryTasklet.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/TableOfContents.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1733

#1744 Update Renovate config
  .github/renovate.json
Labels: ns:em, prd:em, rel:em-stitching-pr-1744

#1773 Em 5551 update renovate config
  .github/renovate.json
Labels: ns:em, prd:em, add-or-update, rel:em-stitching-pr-1773

#1778 Em 5551 update renovate config
  .github/renovate.json
Labels: ns:em, prd:em, rel:em-stitching-pr-1778

#1782 Updated v14 db details for perftest
  infrastructure/perftest.tfvars
Labels: ns:em, prd:em, add-or-update, rel:em-stitching-pr-1782

#1788 EM-5569 Update dependency-check-suppressions.xml
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-1788

#1790 EM-5568 add title for empty outlines
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFOutline.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1790
