Repository hmcts/em-stitching-api, pull requests merged in 2023-05, with the labels that each got.

#1514 EM-5230 avoid CVE-2023-20862
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-1514

#1517 Disabled syncBranchesWithMaster
  Jenkinsfile_CNP
Labels: ns:em, prd:em, rel:em-stitching-pr-1517

#1525 Refer to new AppInsights details
  infrastructure/main.tf
Labels: ns:em, prd:em, add-or-update, rel:em-stitching-pr-1525

#1541 EM-5273 fix flyway issue
  charts/em-stitching/values.preview.template.yaml
  src/main/java/uk/gov/hmcts/reform/em/stitching/data/migration/FlywayCustomConfig.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1541

#1544 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:em, prd:em, rel:em-stitching-pr-1544

#1551 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:em, prd:em, rel:em-stitching-pr-1551
