Repository hmcts/em-stitching-api, pull requests merged in 2023-07, with the labels that each got.

#1605 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-1605

#1590 Em-5118 spring 3 upgrade
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BaseTest.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/DocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/SecureDocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/testutil/TestUtil.java
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/stitching/Application.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/config/BatchConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/config/JacksonConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/config/audit/EntityAuditEventListener.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/config/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/config/security/SecurityUtils.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/AbstractAuditingEntity.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/Bundle.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/BundleContainer.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/BundleDocument.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/BundleFolder.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/Callback.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/DocumentTask.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/EntityAuditEvent.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/PersistentAuditEvent.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/validation/CallableEndpoint.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/domain/validation/CallableEndpointValidator.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/rest/DocumentTaskResource.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/rest/errors/ExceptionTranslator.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/service/CdamService.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/service/dto/BundleDocumentDTO.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/service/dto/CallbackDto.java
  src/main/java/uk/gov/hmcts/reform/em/stitching/service/dto/DocumentTaskDTO.java
  src/main/resources/application.yaml
  src/main/resources/db/migration/V4__batch_job_execution_add_column.sql
  src/test/java/uk/gov/hmcts/reform/em/stitching/repository/CustomAuditEventRepositoryIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/rest/TestSecurityConfiguration.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/rest/WelcomeResourceTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/rest/errors/ExceptionTranslatorIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/rest/errors/ExceptionTranslatorTestController.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1590

#1610 enable syncBranchesWithMaster
  Jenkinsfile_CNP
Labels: ns:em, prd:em, rel:em-stitching-pr-1610

#1611 Upgraded gradle version to 8
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:em, prd:em, rel:em-stitching-pr-1611

#1628 Added in Indexes
  src/main/resources/db/migration/V5__jhi_entity_audit_event_entity_type_entity_id_idx.sql
Labels: ns:em, prd:em, rel:em-stitching-pr-1628

#1629 Reverted serenity & pact lib versions
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-1629

#1640 Updated Hikari connection-timeout
  charts/em-stitching/Chart.yaml
  charts/em-stitching/values.yaml
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-1640

#1654 upgrade spring boot to 3.1.2
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/stitching/testutil/TestUtil.java
  src/aat/resources/file_example_PPT_250kB.ppt
Labels: ns:em, prd:em, rel:em-stitching-pr-1654

#1634 fix outline navigation
  src/main/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFOutline.java
Labels: ns:em, prd:em, rel:em-stitching-pr-1634

#1664 Updated CVE list
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-1664
