Repository hmcts/em-stitching-api, pull requests merged in 2024-08, with the labels that each got.

#2337 Updated log level
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-2337

#2347 EM-6192 add missing fonts
  Dockerfile
  lib/fonts/Helvetica-Bold.ttf
  lib/fonts/Helvetica-BoldOblique.ttf
  lib/fonts/Helvetica-Oblique.ttf
  lib/fonts/Helvetica.ttf
  lib/fonts/helvetica-compressed-5871d14b6903a.otf
  lib/fonts/helvetica-light-587ebe5a59211.ttf
  lib/fonts/helvetica-rounded-bold-5871d05ead8de.otf
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-2347

#2353 Em-6192 add missing other fonts
  lib/fonts/ARIALBOLDITALICMT.OTF
  lib/fonts/ARIALBOLDMT.OTF
  lib/fonts/ARIALMTBLACK.TTF
  lib/fonts/ARIALMTEXTRABOLD.TTF
  lib/fonts/ARIALMTEXTRABOLDITALIC.TTF
  lib/fonts/ARIALMTITALIC.OTF
  lib/fonts/ARIALMTLIGHT.TTF
  lib/fonts/ARIALMTLIGHTITALIC.TTF
  lib/fonts/ARIALMTMEDIUM.TTF
  lib/fonts/ARIALMTMEDIUMITALIC.TTF
  lib/fonts/ARIALMTNARROW.TTF
  lib/fonts/ARIALMTNARROWBOLD.TTF
  lib/fonts/ARIALMTNARROWBOLDITALIC.TTF
  lib/fonts/ARIALMTNARROWITALIC.TTF
  lib/fonts/ARIALROUNDEDMT.TTF
  lib/fonts/ARIALROUNDEDMTEXTRABOLD.TTF
  lib/fonts/ARIALROUNDEDMTLIGHT.TTF
  lib/fonts/ARLRDBD.TTF
  lib/fonts/NotoSans-Bold.ttf
  lib/fonts/NotoSans-BoldItalic.ttf
  lib/fonts/NotoSans-Italic.ttf
  lib/fonts/NotoSans-Regular.ttf
  lib/fonts/arialmt.ttf
  lib/fonts/arialmtblackitalic.ttf
  lib/fonts/zapf-dingbats-regular.ttf
Labels: ns:em, prd:em, rel:em-stitching-pr-2353

#2355 Updated log level
  src/main/java/uk/gov/hmcts/reform/em/stitching/batch/DocumentTaskItemProcessor.java
Labels: ns:em, prd:em, rel:em-stitching-pr-2355

#2356 Em-6192 revert add missing other fonts
  Dockerfile
  lib/fonts/ARIALBOLDITALICMT.OTF
  lib/fonts/ARIALBOLDMT.OTF
  lib/fonts/ARIALMTBLACK.TTF
  lib/fonts/ARIALMTEXTRABOLD.TTF
  lib/fonts/ARIALMTEXTRABOLDITALIC.TTF
  lib/fonts/ARIALMTITALIC.OTF
  lib/fonts/ARIALMTLIGHT.TTF
  lib/fonts/ARIALMTLIGHTITALIC.TTF
  lib/fonts/ARIALMTMEDIUM.TTF
  lib/fonts/ARIALMTMEDIUMITALIC.TTF
  lib/fonts/ARIALMTNARROW.TTF
  lib/fonts/ARIALMTNARROWBOLD.TTF
  lib/fonts/ARIALMTNARROWBOLDITALIC.TTF
  lib/fonts/ARIALMTNARROWITALIC.TTF
  lib/fonts/ARIALROUNDEDMT.TTF
  lib/fonts/ARIALROUNDEDMTEXTRABOLD.TTF
  lib/fonts/ARIALROUNDEDMTLIGHT.TTF
  lib/fonts/ARLRDBD.TTF
  lib/fonts/Helvetica-Bold.ttf
  lib/fonts/Helvetica-BoldOblique.ttf
  lib/fonts/Helvetica-Oblique.ttf
  lib/fonts/Helvetica.ttf
  lib/fonts/NotoSans-Bold.ttf
  lib/fonts/NotoSans-BoldItalic.ttf
  lib/fonts/NotoSans-Italic.ttf
  lib/fonts/NotoSans-Regular.ttf
  lib/fonts/arialmt.ttf
  lib/fonts/arialmtblackitalic.ttf
  lib/fonts/helvetica-compressed-5871d14b6903a.otf
  lib/fonts/helvetica-light-587ebe5a59211.ttf
  lib/fonts/helvetica-rounded-bold-5871d05ead8de.otf
  lib/fonts/zapf-dingbats-regular.ttf
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-2356
