Repository hmcts/em-stitching-api, pull requests merged in 2024-12, with the labels that each got.

#2518 Upgrade pact to 4.6.15, set idamconsumertest to v3 spec
  Jenkinsfile_CNP
  build.gradle
  src/contractTest/java/uk/gov/hmcts/reform/em/stitching/IdamConsumerTest.java
Labels: ns:em, prd:em, rel:em-stitching-pr-2518

#2538 EM-6354 drop document task table
  src/main/resources/db/migration/V15__drop_document_task_table.sql
Labels: ns:em, prd:em, aat/no-changes, prod/no-changes, rel:em-stitching-pr-2538

#2544 Create SECURITY.md
  SECURITY.md
Labels: ns:em, prd:em, rel:em-stitching-pr-2544

#2539 CME:123: add db monitoring
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:em, prd:em, aat/add-or-update, prod/add-or-update, rel:em-stitching-pr-2539
