Repository hmcts/em-stitching-api, pull requests merged in 2024-01, with the labels that each got.

#1963 Readded in v15 db details
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/variables.tf
Labels: ns:em, prd:em, add-or-update, rel:em-stitching-pr-1963

#1968 Removed redundant s2s keys
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-1968

#1975 Em 5744 resolve CVE
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-stitching-pr-1975

#1996 Updated in force_user_permissions_trigger to recreate DB roles
  infrastructure/main.tf
Labels: ns:em, prd:em, destroy, rel:em-stitching-pr-1996

#1998 Reverted v15 db details
  infrastructure/main.tf
Labels: ns:em, prd:em, destroy, rel:em-stitching-pr-1998

#2000 Em 5525 recreate roles aat v15 db 2
  infrastructure/main.tf
Labels: ns:em, prd:em, add-or-update, rel:em-stitching-pr-2000

#2002 Em 5525 recreate roles aat v15 db 2
  infrastructure/main.tf
Labels: ns:em, prd:em, destroy, rel:em-stitching-pr-2002

#2003 Em 5525 recreate roles aat v15 db 2
  infrastructure/main.tf
Labels: ns:em, prd:em, destroy, rel:em-stitching-pr-2003

#2005 Reduced v15 DB core for Prod
  infrastructure/prod.tfvars
Labels: ns:em, prd:em, no-changes, rel:em-stitching-pr-2005

#2011 Updated v15 db mappings and secrets
  charts/em-stitching/Chart.yaml
  charts/em-stitching/values.yaml
  infrastructure/main.tf
Labels: ns:em, prd:em, add-or-update, rel:em-stitching-pr-2011

#2012 add graceful shutdown
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-2012

#2013 Removed v11 DB and related config
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:em, prd:em, destroy, rel:em-stitching-pr-2013

#2017 Upgrading to Java 21
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-2017

#2021 Upgrading pitest to 1.15.0
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-2021

#2022 Updated deletion config
  charts/em-stitching/Chart.yaml
  charts/em-stitching/values.yaml
Labels: ns:em, prd:em, rel:em-stitching-pr-2022
