Repository hmcts/em-stitching-api, pull requests merged in 2025-01, with the labels that each got.

#2562 Tests updated to use JUnit5 annotations
  src/test/java/uk/gov/hmcts/reform/em/stitching/batch/DocumentTaskCallbackProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/batch/DocumentTaskItemProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/batch/RemoveOldDocumentTaskTaskletTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/batch/UpdateDocumentTaskTaskletTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/config/security/SecurityUtilsTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/conversion/ImageConverterTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/conversion/PDFConverterTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/domain/BundleTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/domain/CallbackTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/domain/DocumentTaskTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/domain/EntityAuditEventTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/domain/PageNumberFormatTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/domain/PaginationStyleTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/domain/validation/CallableEndpointValidatorTest.java
Labels: ns:em, prd:em, rel:em-stitching-pr-2562

#2563 Tests updated to use JUnit5 annotations
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMergerCoversheetsTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFMergerTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFOutlineTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/pdf/PDFWatermarkTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/repository/CustomAuditEventRepositoryIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/repository/CustomAuditEventRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/repository/IdamRepositoryTest.java
Labels: ns:em, prd:em, rel:em-stitching-pr-2563

#2587 Upgraded to JUnit5 and updated correct imports 4
  src/test/java/uk/gov/hmcts/reform/em/stitching/service/impl/DmStoreDownloaderImplTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/service/impl/DmStoreUploaderImplTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/service/impl/DmStoreUriFormatterTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/service/impl/DocumentConversionServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/service/impl/StringFormattingUtilsTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/template/DocmosisClientExceptionTest.java
Labels: ns:em, prd:em, aat/no-changes, prod/no-changes, rel:em-stitching-pr-2587

#2578 Upgraded to JUnit5 and updated annotations 3
  src/test/java/uk/gov/hmcts/reform/em/stitching/rest/DocumentTaskResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/rest/WelcomeResourceTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/rest/errors/ExceptionTranslatorIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/service/CdamServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/template/DocmosisClientRenderTest.java
  src/test/java/uk/gov/hmcts/reform/em/stitching/template/DocmosisClientWatermarkTest.java
Labels: ns:em, prd:em, aat/no-changes, prod/no-changes, rel:em-stitching-pr-2578

#2607 EM-6408 fix pitests
  build.gradle
Labels: ns:em, prd:em, aat/no-changes, prod/no-changes

#2588 Em 6343 migrate junit5: functional tests
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BaseTest.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleFolderScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleOptionScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BundleOutlineScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/DocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/OpenIdConnectScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/SecureDocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/stitching/smoke/SmokeTest.java
Labels: ns:em, prd:em

#2610 EM-6343: revert smoketest
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/stitching/smoke/SmokeTest.java
Labels: ns:em, prd:em

#2597 upgrade em-test-helper to 2.1.1
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/stitching/functional/BaseTest.java
Labels: ns:em, prd:em

#2625 EM-6343 Removing JUnit4 Dependencies
  build.gradle
Labels: ns:em, prd:em, rel:em-stitching-pr-2625
